### ISSUE TITLE
.

### ISSUE THREAD

**Issue by FeryN77** [ipr0gr4mipas2/GrowtopiaServer#11]
My question

**Comment by iProgramMC** [comment]
What's wamp?

**Comment by FeryN77** [comment]
> What's wamp?

Wamp server

**Comment by FeryN77** [comment]
> What's wamp?

Make tutorial how to use nginx

**Comment by iProgramMC** [comment]
What is that? Don't you mean XAMPP?

**Comment by iProgramMC** [comment]
And there are already tutorials on how to do it.

**Comment by FeryN77** [comment]
I ask how to use Nginx Http server / wamp server bcz i dont know how to use http server  nginx / wamp server

**Comment by FeryN77** [comment]
> And there are already tutorials on how to do it.

Can U make How to use Nginx Http server ?

**Comment by iProgramMC** [comment]
No, google.com is your best friend 🙂

**Comment by MoanHawks** [comment]
Simple from python 

import http.server
print("Set up HTTP server")

class ServerHandler(http.server.BaseHTTPRequestHandler):
			def do_POST(self):
				self.send_response(200)
				self.end_headers()
				self.wfile.write(str.encode("server|127.0.0.1\nport|17091\ntype|1\n#maint|Mainetrance message (Not used for now) -- Growtopia Noobs\n\nbeta_server|127.0.0.1\nbeta_port|17091\n\nbeta_type|1\nmeta|localhost\nRTENDMARKERBS1001"))
		server_address = ('', 80)
		httpd = http.server.HTTPServer(server_address, ServerHandler)
		print("HTTP server is running.")
		httpd.serve_forever()

**Comment by iProgramMC** [comment]
He meant using nginx

**Comment by FeryN77** [comment]
Nginx Not py :|

**Comment by GrowtopiaNoobs2** [comment]
Wampp

**Comment by GuckTubeYT** [comment]
> What's wamp?

thats like XAMPP, but, WAMP Use Nginx
Maybe...

**Comment by FeryN77** [comment]
I ask How To use Nginx / wamp server :|
But no one can help mi

**Comment by JadlionHD** [comment]
> I ask How To use Nginx / wamp server :|
> But no one can help mi

that's because, they're dont know what do you mean.

**Comment by FeryN77** [comment]
> > I ask How To use Nginx / wamp server :|
> > But no one can help mi
> 
> that's because, they're dont know what do you mean.

what I mean is how to run nginx http server for growtopia private server

**Comment by arshizx** [comment]
> > > I ask How To use Nginx / wamp server :|
> > > But no one can help mi
> > 
> > 
> > that's because, they're dont know what do you mean.
> 
> what I mean is how to run nginx http server for growtopia private server

just use google /fp
