### ISSUE TITLE
[QUESTION] How can I fix "packet drop" problem?

### ISSUE THREAD

**Issue by ghost** [ipr0gr4mipas2/GrowtopiaServer#13]
When I build this source and run the server, i got "packet drop" and it stay on "Logging in...". So, what is the problem and how can I fix it, or is it build failed problem?

**Comment by iProgramMC** [comment]
You need to have an items.dat. If you are using Visual Studio to run it (Start Windows Debugger option), it's usually where the ENet server test.cpp file is. Otherwise, it's where the enet server test.exe file is. It's good to have it in both places. Also, make sure you have a players and worlds folder there too, or else it will have issues.

**Comment by ghost** [comment]
I have 3.37 items.dat and i use exe with building it. I have worlds and players folder.

**Comment by iProgramMC** [comment]
> I have 3.37 items.dat and i use exe with building it. I have worlds and players folder.

Do you have it where the players and worlds folders are? Try both where ENet server test.cpp is and where ENet server test.exe is.

**Comment by ghost** [comment]
Sure, let me try it.

**Comment by iProgramMC** [comment]
Also, the "packet drop" is because the game requests items multiple times, which isn't accepted.

**Comment by ghost** [comment]
Does it means because of "packet drop" problem is items.dat?

**Comment by iProgramMC** [comment]
No, it's normal Growtopia behavior.

**Comment by ghost** [comment]
By the way, does enet server test.exe needs CoreData.txt and Descriptions.txt?

**Comment by iProgramMC** [comment]
The coredata is not really needed, as it loads item defs from items.dat
directly, but if you want item infos, you will need descriptions.txt.

**Comment by ghost** [comment]
When I debug exe, it says: "std::bad_array_new_length. Memory address: 0x007CBF68." and throw exception. I copied updated items.dat, created worlds and players folder.

**Comment by iProgramMC** [comment]
No idea how to help with this, sorry.

**Comment by ghost** [comment]
It gives that exception on this line: `char* data = new char[size];` in `buildItemsDatabase` method. Really you haven't any idea?

**Comment by iProgramMC** [comment]
No, I don't

**Comment by ghost** [comment]
Thanks, have a good day!

**Comment by ghost** [comment]
It fixed itself suddenly, closing issue.
