### ISSUE TITLE
[QUESTION] I can't break any block.

### ISSUE THREAD

**Issue by ghost** [ipr0gr4mipas2/GrowtopiaServer#14]
I am newbie at coding growtopia server. I have a problem again. When I punch or place, it didn't give any reaction to me. Someone can help to me?

**Comment by GrowtopiaNoobs2** [comment]
Use code in my repo!

**Comment by iProgramMC** [comment]
> Use code in my repo!

Do not, he looks fake. Please confirm that in the growtopiaserver2 development discord server.

**Comment by ghost** [comment]
I know he is fake, is there any idea about my problem?

**Comment by hadessg** [comment]
He is fake, anybody said in the discord server

**Comment by ghost** [comment]
No answer, closing issue.
