### ISSUE TITLE
This not origin repo

### ISSUE THREAD

**Issue by GrowtopiaNoobs2** [ipr0gr4mipas2/GrowtopiaServer#19]

**Comment by iProgramMC** [comment]
This was the first fork of the original repo, and all the other forks went to mine 🙂

**Comment by GrowtopiaNoobs2** [comment]
Iprogramc i was think u my friends. But i dont now so if you dont close repo ill send dmca copyright strike

**Comment by iProgramMC** [comment]
> Iprogramc i was think u my friends. But i dont now so if you dont close repo ill send dmca copyright strike

You never talk like that. What do you copyright strike? If you do I'll send a counterstrike back. Why are you even mad, anyway?
