### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by hadessg** [ipr0gr4mipas2/GrowtopiaServer#2]
Wouldn't this go against the whole point of the DMCA, likely this will be taken down and you are breaking copyright law. I would suggest instead of a Github page even though how accesible it is, we all work with the discord server set up by GrowtopiaNoobs/Anybody. Thanks!

Link: https://discord.gg/Skw2QDq

**Comment by Hades3377** [comment]
NOTE: I DO NOT OWN THE DISCORD, IT WAS MADE BY GROWTOPIANOOBS HIMSELF.

**Comment by raiterjaki** [comment]
NOTE:

**Comment by Hades3377** [comment]
big lol big funny raiterjaki!!!

**Comment by Syn9673** [comment]
@Hades3377 well, if Ubisoft really wanted this gone, they could also contact discord and get that discord server deleted. But i highly doubt that they have time to do that.

**Comment by hadessg** [comment]
lol they had the time to take down the original one, also i personally feel it would be easier communication and less trolling on discord.

**Comment by hadessg** [comment]
Closed because i think this will become the new repo.

**Comment by iProgramMC** [comment]
@Hades3377 Yes, it might. They should have been more careful to include all the 118 forks.
