### ISSUE TITLE
3.38 Disconnecting

### ISSUE THREAD

**Issue by arshizx** [ipr0gr4mipas2/GrowtopiaServer#31]
**Describe the bug**
Sometimes when you entering worlds you will disconnected.

**To Reproduce**
1. Enter a World
2. Leave the World
3. Repeat that 3-5 Times. & it will disconnecting

**Expected behavior**
Not Disconnected

**Desktop (please complete the following information):**
 - Version [V3.38]

**Additional context**
Maybe because action|getDRAnimations, but im not sure.

**Comment by iProgramMC** [comment]
action|getDRAnimations, never heard of it?

**Comment by atomiclucky** [comment]
that's why it only happens on 3.38. Maybe a new packet?

**Comment by iProgramMC** [comment]
Try using a proxy and seeing what's wrong

**Comment by iProgramMC** [comment]
I mean, how real GT responds to that packet

**Comment by arshizx** [comment]
i'm seeing this packet 
```
param 0: UpdateOwnedRespawnAnim
param 1: 0
param 0: UpdateOwnedDeathAnim
param 1: 0
```
spamming when in world menu / its send 2 times when entering world with the action|getDRAnimations too

**Comment by MoanHawks** [comment]
Try this if working 

if (cch.find("action|getDRAnimations") != 
string::npos) 

Then Create the packet of UpdateOwnedRespawnAnim and UpdateOwnedDeathAnim

**Comment by arshizx** [comment]
still, i try that already before i open this issue & im disconecting when i got action|getDRAnimations only 1 times

**Comment by atomiclucky** [comment]
Well I don't get disconnected on 3.38 from my testings

**Comment by arshizx** [comment]
> 
> 
> Well I don't get disconnected on 3.38 from my testings

try that 2-5 alrd? or maybe cause the world
