### ISSUE TITLE
Game crash on enter

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [ipr0gr4mipas2/GrowtopiaServer#40]
**Describe the bug**
When entering a world a blank world without a character appears and then the client crashes.

**To Reproduce**
1. Log in to server
2. Enter a world
3. Game client crashes

**Expected behavior**
Expected the world to load correctly with no crash.

**Screenshots**
Right before crash:
https://macaylamarvelous81.is-inside.me/NfPzVjm2.png

**Desktop (Client) (please complete the following information):**
 - OS: Windows 10
 - Version 3.45

**Server:**
 - OS: Raspberry Pi OS
 - Version: c87fa15

**Additional context**
None

**Comment by MacaylaMarvelous81** [comment]
The same issue occurs on Android (connecting to the same server)

**Comment by MacaylaMarvelous81** [comment]
The same issue occurs when running the server on Windows 10

**Comment by Syn9673** [comment]
texture files problem, just update your items.dat and cdncontent

**Comment by MacaylaMarvelous81** [comment]
Thanks, I did not realize the CDNContent and items.dat was not with the same version
