### ISSUE TITLE
fake bitch a$$.

### ISSUE THREAD

**Issue by GrowtopiaNoobs2** [ipr0gr4mipas2/GrowtopiaServer#5]
Check my repo

**Comment by SWE827** [comment]
What Happend With Source Code?

**Comment by GrowtopiaNoobs2** [comment]
> What Happend With Source Code?

We got copyright from ubisoft

**Comment by GuckTubeYT** [comment]
Ubigay lol

**Comment by ipr0gr4mipas2** [comment]
Would have liked if I could have just allowed you to handle PRs, since this is the "base" where every other repo is forked from.

**Comment by ipr0gr4mipas2** [comment]
@GrowtopiaNoobs @GrowtopiaNoobs2 https://github.com/ipr0gr4mipas2/GrowtopiaServer/invitations check this and accept the invite

**Comment by herothedev** [comment]
I don't think so GTNoobs2 is real smh but ok

**Comment by ipr0gr4mipas2** [comment]
@herothedev yes

**Comment by Hades3377** [comment]
imagine spy ubisoft 😳

**Comment by GuckTubeYT** [comment]
lol
