### ISSUE TITLE
[QUESTION] how fix crasher???

### ISSUE THREAD

**Issue by FeryN77** [ipr0gr4mipas2/GrowtopiaServer#6]
Some one know? How to fix
Crasher?
Someone Crash my server and I cant run exe

**Comment by hadessg** [comment]
first find the method of crashing.

**Comment by cmdocmd** [comment]
you should know how the crashing

**Comment by ipr0gr4mipas2** [comment]
I doubt that someone is out there 24/7 crashing your server. Maybe your server crashes upon start, try running it in visual studio debug mode. Anyways, you said that you can't run the exe. Perhaps it's another issue.
